### ISSUE TITLE
preview deletes manifest.json

### ISSUE THREAD

**Issue by erdmann040** [kucrut/vite-for-wp-example-vanilla-js#2]
Hi there,

I have installed the plugin as described in the readme.

$ npm run dev 

and the Hot Module Replacement work perfectly.

$ npm run build

generates the bundle files and a manifest.json

├── app
│ ├── dist
│ │ ├─── assets
│ │ │ ├─── main-3334f76a.css
│ │ │ ├─── main-cb3656f0.js
│ │ │ └─── main-cb3656f0.js.map
│ │ └─── manifest.json

So everythings fine so far. But if I use 

$ npm run preview 

the manifest.json is deleted and if I open the page 

http://localhost:4173/

in the browser I get an error message

"Cannot GET /"

Under the local domain, which I have set up using the tool Local (by Flywheel), I get the following error message:

"[Vite] No manifest found in /home/jan/local-sites/wal21/app/public/wp-content/plugins/my-plugin/app/dist."

Can you reproduce this error?  
Or is it due to my local WordPress setup and missing settings? 
Is it intentional that the manifest.json is deleted or is this a bug?

Thanks in advance for your help

**Comment by kucrut** [comment]
@erdmann040 Thanks for the report.

Unfortunately I'm not able to reproduce this issue. I ran build and then preview but my `manifest.json` is not deleted.

Having said that, I don't think you need to run preview at all. After running `npm run build`, refresh the page that uses the script and the built script should be loaded. Please let me know otherwise.

In the mean time, I'll go ahead and remove the `preview` script from `package.json`.

**Comment by erdmann040** [comment]
Thanks for the reply. Maybe the error is somewhere on my side. I'll try again with a completely fresh WordPress site. Maybe some sideeffect, due to a plugin, my development environment or something similar. When I know more, I'll get back to you.

**Comment by erdmann040** [comment]
Hi, when I did a new WordPress installation and used a default theme, the `manifest.json` was no longer deleted when I ran the `node run preview` command. So must be something I screwed up myself (havent found yet). Sorry and thanks for the help!
